/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modul1;

/**
 *
 * @author Lenovo
 */
public class Modul9 extends javax.swing.JFrame {

    /**
     * Creates new form Modul9
     */
    public Modul9() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sNormal = new javax.swing.JSpinner();
        sAngka = new javax.swing.JSpinner();
        sHari = new javax.swing.JSpinner();
        sTanggal = new javax.swing.JSpinner();
        jfNormal = new javax.swing.JTextField();
        jfAngka = new javax.swing.JTextField();
        jfHari = new javax.swing.JTextField();
        jfTanggal = new javax.swing.JTextField();
        jNormal = new javax.swing.JLabel();
        jAngka = new javax.swing.JLabel();
        jHari = new javax.swing.JLabel();
        jTanggal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sNormal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sNormalStateChanged(evt);
            }
        });

        sAngka.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sAngkaStateChanged(evt);
            }
        });

        sHari.setModel(new javax.swing.SpinnerListModel(new String[] {"Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu"}));
        sHari.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sHariStateChanged(evt);
            }
        });

        sTanggal.setModel(new javax.swing.SpinnerDateModel());
        sTanggal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sTanggalStateChanged(evt);
            }
        });

        jfNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfNormalActionPerformed(evt);
            }
        });

        jfAngka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfAngkaActionPerformed(evt);
            }
        });

        jfHari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfHariActionPerformed(evt);
            }
        });

        jfTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfTanggalActionPerformed(evt);
            }
        });

        jNormal.setText("Normal");

        jAngka.setText("Angka");

        jHari.setText("Hari");

        jTanggal.setText("Tanggal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jNormal))
                    .addComponent(jfNormal, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(sNormal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jAngka)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jfAngka, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(sAngka))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jHari)
                                .addGap(61, 61, 61))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jfHari, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jfTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(jTanggal))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(sHari, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(121, 121, 121))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAngka)
                    .addComponent(jTanggal)
                    .addComponent(jHari)
                    .addComponent(jNormal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sNormal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sAngka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jfNormal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfAngka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jfTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(140, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void jfAngkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfAngkaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jfAngkaActionPerformed

    private void jfNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfNormalActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jfNormalActionPerformed

    private void jfHariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfHariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfHariActionPerformed

    private void jfTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jfTanggalActionPerformed

    private void sAngkaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sAngkaStateChanged
        jfAngka.setText(sAngka.getValue().toString());
    }//GEN-LAST:event_sAngkaStateChanged

    private void sNormalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sNormalStateChanged
        jfNormal.setText(sNormal.getValue().toString());        
    }//GEN-LAST:event_sNormalStateChanged

    private void sHariStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sHariStateChanged
        jfHari.setText(sHari.getValue().toString());
    }//GEN-LAST:event_sHariStateChanged

    private void sTanggalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sTanggalStateChanged
        jfTanggal.setText(sTanggal.getValue().toString());
    }//GEN-LAST:event_sTanggalStateChanged
    
                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modul9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modul9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modul9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modul9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modul9().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jAngka;
    private javax.swing.JLabel jHari;
    private javax.swing.JLabel jNormal;
    private javax.swing.JLabel jTanggal;
    private javax.swing.JTextField jfAngka;
    private javax.swing.JTextField jfHari;
    private javax.swing.JTextField jfNormal;
    private javax.swing.JTextField jfTanggal;
    private javax.swing.JSpinner sAngka;
    private javax.swing.JSpinner sHari;
    private javax.swing.JSpinner sNormal;
    private javax.swing.JSpinner sTanggal;
    // End of variables declaration//GEN-END:variables
}
