/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package modul1;
import javax.swing.JOptionPane;
/**
 *
 * @author Lenovo
 */
public class Modul2 extends javax.swing.JFrame {
    
    /**
     * Creates new form formsoal
     */
    public Modul2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eNIM = new javax.swing.JLabel();
        eNAMA = new javax.swing.JLabel();
        eALAMAT1 = new javax.swing.JLabel();
        eNOTELEPON1 = new javax.swing.JLabel();
        fieldNim = new javax.swing.JTextField();
        fieldNama = new javax.swing.JTextField();
        fieldAlamat = new javax.swing.JTextField();
        fieldNoTelp = new javax.swing.JTextField();
        JLabel = new javax.swing.JButton();
        JOption = new javax.swing.JButton();
        eNAMA1 = new javax.swing.JLabel();
        eALAMAT = new javax.swing.JLabel();
        eNOTELEPON = new javax.swing.JLabel();
        fieldnama1 = new javax.swing.JTextField();
        fieldalamat2 = new javax.swing.JTextField();
        fieldtelepon2 = new javax.swing.JTextField();
        fieldNim4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextfield = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fieldNim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNimActionPerformed(evt);
            }
        });

        fieldNoTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNoTelpActionPerformed(evt);
            }
        });

        JLabel.setText("JLabel");
        JLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JLabelActionPerformed(evt);
            }
        });

        JOption.setText("JOptionPane");
        JOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JOptionActionPerformed(evt);
            }
        });

        eNAMA1.setText("NAMA  ");

        eALAMAT.setText("ALAMAT");

        eNOTELEPON.setText("TELEPON");

        fieldnama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldnama1ActionPerformed(evt);
            }
        });

        fieldalamat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldalamat2ActionPerformed(evt);
            }
        });

        fieldtelepon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldtelepon2ActionPerformed(evt);
            }
        });

        fieldNim4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNim4ActionPerformed(evt);
            }
        });

        jLabel1.setText("NIM");

        jTextfield.setText("JTextField");
        jTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextfieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eNAMA1)
                            .addComponent(eALAMAT)
                            .addComponent(eNOTELEPON)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(eNIM)
                                    .addComponent(eNAMA)
                                    .addComponent(eALAMAT1)))
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(fieldNoTelp, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                        .addComponent(fieldAlamat))
                                    .addComponent(fieldNim, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldnama1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldNim4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldalamat2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldtelepon2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(JOption)
                        .addGap(18, 18, 18)
                        .addComponent(JLabel)
                        .addGap(18, 18, 18)
                        .addComponent(jTextfield))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(eNOTELEPON1)))
                .addGap(0, 99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eNAMA1)
                    .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eALAMAT))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eNOTELEPON))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel)
                    .addComponent(JOption)
                    .addComponent(jTextfield))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fieldNim4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eNAMA)
                            .addComponent(fieldnama1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eALAMAT1)
                            .addComponent(fieldalamat2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eNOTELEPON1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fieldtelepon2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eNIM)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNoTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNoTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNoTelpActionPerformed

    private void fieldNimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNimActionPerformed

    private void JLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JLabelActionPerformed
        // TODO add your handling code here:
        String nim = fieldNim.getText();
        String nama = fieldNama.getText();
        String alamat = fieldAlamat.getText();
        
        eNIM.setText("NIM: " + nim);
        eNAMA.setText("Nama: " + nama);
        eALAMAT1.setText("Alamat: " + alamat);
        
        
    }//GEN-LAST:event_JLabelActionPerformed

    private void JOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JOptionActionPerformed
        // TODO add your handling code here
        String nim = fieldNim.getText();
        String nama = fieldNama.getText();
        JOptionPane.showMessageDialog(this, "NIM: " + nim + "\nNAMA: " + nama);
    }//GEN-LAST:event_JOptionActionPerformed

    private void fieldnama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldnama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldnama1ActionPerformed

    private void fieldalamat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldalamat2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldalamat2ActionPerformed

    private void fieldtelepon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldtelepon2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldtelepon2ActionPerformed

    private void fieldNim4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNim4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNim4ActionPerformed

    private void jTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextfieldActionPerformed
        // TODO add your handling code here:
        String nim = fieldNim.getText();
        String nama = fieldNama.getText();
        String alamat = fieldAlamat.getText();
        String noTelp = fieldNoTelp.getText();
        
        fieldNim4.setText(" " + nim);
        fieldnama1.setText(" " + nama);
        fieldalamat2.setText(" " + alamat);
        fieldtelepon2.setText(" " + noTelp);
    }//GEN-LAST:event_jTextfieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modul2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modul2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modul2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modul2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modul2().setVisible(true);
            }
        });
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JLabel;
    private javax.swing.JButton JOption;
    private javax.swing.JLabel eALAMAT;
    private javax.swing.JLabel eALAMAT1;
    private javax.swing.JLabel eNAMA;
    private javax.swing.JLabel eNAMA1;
    private javax.swing.JLabel eNIM;
    private javax.swing.JLabel eNOTELEPON;
    private javax.swing.JLabel eNOTELEPON1;
    private javax.swing.JTextField fieldAlamat;
    private javax.swing.JTextField fieldNama;
    private javax.swing.JTextField fieldNim;
    private javax.swing.JTextField fieldNim4;
    private javax.swing.JTextField fieldNoTelp;
    private javax.swing.JTextField fieldalamat2;
    private javax.swing.JTextField fieldnama1;
    private javax.swing.JTextField fieldtelepon2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jTextfield;
    // End of variables declaration//GEN-END:variables
}
